/**
 * "Explain this comparison" (#613, Phase 3): a button that sends the numbers
 * on the page to `POST public/cloud-tools/explain` and shows the two
 * paragraphs that come back, labelled as generated.
 *
 * ONLY ON A CLICK. Nothing here fetches on mount, on a scenario change or on
 * a region change: an explanation costs a model call and counts against the
 * reader's five an hour, so it is asked for, never assumed. The answer is
 * keyed to the exact numbers it explained — change an extra and the panel
 * goes away rather than describing a total that is no longer on the page —
 * and that key is compared during render, so there is no effect and no
 * setState in one.
 *
 * DISABLED WHILE ANY TOTAL IS NULL. An "unavailable" provider has nothing to
 * explain, and the server would be asked to reason about a missing number.
 */
import React, { useState } from 'react';
import { Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { formatLocalDateTime } from '@/lib/cloudPricing';
import { requestPricingExplanation } from '@/lib/publicApi';
import { scenarioById } from '@/lib/pricingScenarios';

/**
 * The request body: the computed comparison, trimmed to what the server's
 * prompt uses (provider, total, base, the segments' id, label and cost, and
 * the unavailable list). Lines are left out on purpose — they are what keeps
 * a body under the 8 KB cap.
 */
export function explanationRequest({ region, result }) {
  return {
    region,
    scenarioId: result.scenarioId,
    scenarioLabel: scenarioById(result.scenarioId).label,
    extras: [...result.extras],
    egressGb: result.quantities['edge-cdn'],
    results: result.providers.map((p) => ({
      provider: p.provider,
      total: p.total,
      base: p.base.total,
      segments: p.segments.map(({ extraId, label, cost }) => ({ extraId, label, cost })),
      unavailable: [...p.unavailable],
    })),
  };
}

const paragraphs = (text) =>
  String(text)
    .split(/\n\s*\n/)
    .map((s) => s.trim())
    .filter(Boolean);

function Explanation({ explanation }) {
  return (
    <div
      className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm dark:border-slate-700 dark:bg-slate-900"
      data-testid="explanation"
      data-cached={explanation.cached ? 'true' : undefined}
    >
      <p className="text-xs font-medium uppercase tracking-wider text-slate-600 dark:text-slate-400">
        Generated by AI from the numbers above — check the sources before relying on it
      </p>
      {paragraphs(explanation.text).map((paragraph, index) => (
        <p key={index} className="text-slate-800 dark:text-slate-200">
          {paragraph}
        </p>
      ))}
      <p className="text-xs text-slate-600 dark:text-slate-400">
        {explanation.model} · {formatLocalDateTime(explanation.generatedAt)}
        {explanation.cached
          ? ' · cached: the same numbers were explained recently, so this is that answer'
          : ''}
      </p>
    </div>
  );
}

function Failure({ error, onRetry }) {
  let text;
  if (error.status === 429)
    text = 'Explanations are limited to a few an hour. Try again in a while.';
  else if (error.status === 503) text = error.message;
  else text = `The explanation could not be generated: ${error.message}`;
  return (
    <div
      role="alert"
      className="flex flex-wrap items-center gap-3 rounded-lg border border-destructive/40 bg-destructive/5 p-3 text-sm"
      data-status={error.status ?? 'error'}
    >
      <p className="min-w-0 flex-1 break-words">{text}</p>
      {error.status === 429 || error.status === 503 ? null : (
        <Button variant="outline" size="sm" onClick={onRetry}>
          <RefreshCw className="mr-2 h-3.5 w-3.5" /> Retry
        </Button>
      )}
    </div>
  );
}

/**
 * @param {object} props
 * @param {string} props.region
 * @param {ReturnType<typeof import('@/lib/pricingScenarios').computeScenario>} props.result
 */
export function ExplainButton({ region, result }) {
  const body = explanationRequest({ region, result });
  const key = JSON.stringify(body);
  // One record: which numbers it is about, and where the request got to.
  const [state, setState] = useState(null);
  const current = state?.key === key ? state : null;
  const unavailable = result.providers.some((p) => p.total === null);

  const ask = () => {
    setState({ key, status: 'loading' });
    requestPricingExplanation(body).then(
      (explanation) =>
        setState((prev) => (prev?.key === key ? { key, status: 'done', explanation } : prev)),
      (error) => setState((prev) => (prev?.key === key ? { key, status: 'error', error } : prev))
    );
  };

  return (
    <>
      <Button
        type="button"
        variant="outline"
        size="sm"
        onClick={ask}
        disabled={unavailable || current?.status === 'loading'}
        title={
          unavailable
            ? 'Every provider needs a total before the comparison can be explained.'
            : 'Ask the AI provider for two paragraphs about these numbers.'
        }
        data-testid="explain-button"
      >
        {current?.status === 'loading' ? (
          <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" aria-hidden="true" />
        ) : (
          <Sparkles className="mr-2 h-3.5 w-3.5" aria-hidden="true" />
        )}
        {current?.status === 'loading' ? 'Explaining…' : 'Explain this comparison'}
      </Button>
      {current?.status === 'done' ? (
        <div className="basis-full">
          <Explanation explanation={current.explanation} />
        </div>
      ) : null}
      {current?.status === 'error' ? (
        <div className="basis-full">
          <Failure error={current.error} onRetry={ask} />
        </div>
      ) : null}
    </>
  );
}
