/**
 * "Explain this comparison" (#613, Phase 3): a button that sends the numbers
 * on the page to `POST public/cloud-tools/explain` and shows the two
 * paragraphs that come back, labelled as generated. The button, the answer
 * panel, the failure panel and the click-only rule are ../explain/
 * ExplainControl.jsx, shared with the Landing Zone Builder's button (#670);
 * this file is what the pricing page sends and the words it uses.
 *
 * DISABLED WHILE ANY TOTAL IS NULL. An "unavailable" provider has nothing to
 * explain, and the server would be asked to reason about a missing number.
 */
import React from 'react';
import { requestPricingExplanation } from '@/lib/publicApi';
import { scenarioById } from '@/lib/pricingScenarios';
import { ExplainControl } from '../explain/ExplainControl';

/**
 * The request body: the computed comparison, trimmed to what the server's
 * prompt uses (provider, total, base, the segments' id, label and cost, and
 * the unavailable list). Lines are left out on purpose — they are what keeps
 * a body under the 8 KB cap.
 */
export function explanationRequest({ region, result }) {
  return {
    region,
    scenarioId: result.scenarioId,
    scenarioLabel: scenarioById(result.scenarioId).label,
    extras: [...result.extras],
    egressGb: result.quantities['edge-cdn'],
    results: result.providers.map((p) => ({
      provider: p.provider,
      total: p.total,
      base: p.base.total,
      segments: p.segments.map(({ extraId, label, cost }) => ({ extraId, label, cost })),
      unavailable: [...p.unavailable],
    })),
  };
}

const LABELS = Object.freeze({
  idle: 'Explain this comparison',
  busy: 'Explaining…',
  generated: 'Generated by AI from the numbers above — check the sources before relying on it',
  cached: 'cached: the same numbers were explained recently, so this is that answer',
});

/**
 * @param {object} props
 * @param {string} props.region
 * @param {ReturnType<typeof import('@/lib/pricingScenarios').computeScenario>} props.result
 */
export function ExplainButton({ region, result }) {
  const unavailable = result.providers.some((p) => p.total === null);
  return (
    <ExplainControl
      body={explanationRequest({ region, result })}
      request={requestPricingExplanation}
      labels={LABELS}
      disabled={unavailable}
      title={
        unavailable
          ? 'Every provider needs a total before the comparison can be explained.'
          : 'Ask the AI provider for two paragraphs about these numbers.'
      }
      testIds={{ button: 'explain-button', panel: 'explanation' }}
    />
  );
}
