/**
 * The pure half of ImageDetailsDialog (ADR 0033): the form round-trips the
 * record, the facts drop what is unknown, and the sentences say what the
 * dialog used to say inline.
 */
import { describe, it, expect } from 'vitest';
import { COMMON_PROVIDERS, LICENSE_OPTIONS, SLOT_OPTIONS } from '@/lib/imageGallery';
import {
  deleteDescription,
  factRows,
  FIELD_SPECS,
  fieldsFrom,
  fieldsToPatch,
  lineageSentence,
  selectOptions,
} from './imageDetailsFields';

const ITEM = {
  id: 'img-1',
  galleryCollection: 'generated_content_images',
  title: 'Alpha',
  altText: 'A diagram',
  customTags: ['cloud', 'edge'],
  folder: 'aws',
  provider: 'AWS',
  slot: 'hero',
  source: 'ai-cover',
  imageProvider: 'openai',
  imageModel: 'gpt-image-1',
  promptSet: 'Azure Chibi',
  promptName: 'hero',
  width: 1920,
  height: 1080,
  format: 'png',
  bytes: 2048,
  createdAt: '2026-09-01T10:00:00Z',
};

describe('fieldsFrom and fieldsToPatch', () => {
  it('round-trip the record, with tags as one comma-separated line', () => {
    const fields = fieldsFrom(ITEM);
    expect(fields.tags).toBe('cloud, edge');
    expect(fields.provider).toBe('aws');
    expect(fields.license).toBe('');
    expect(fieldsToPatch(fields)).toMatchObject({
      title: 'Alpha',
      altText: 'A diagram',
      customTags: ['cloud', 'edge'],
      folder: 'aws',
      provider: 'aws',
      slot: 'hero',
    });
  });

  it('give an empty form for no item', () => {
    expect(fieldsFrom(null)).toEqual({
      title: '',
      altText: '',
      caption: '',
      license: '',
      credit: '',
      tags: '',
      folder: 'default',
      provider: '',
      slot: '',
    });
  });

  it('drop blank tags on the way back', () => {
    const patch = fieldsToPatch({ ...fieldsFrom(null), tags: ' a ,, b, ' });
    expect(patch.customTags).toEqual(['a', 'b']);
  });

  it('name every editable field once, with an id for its label', () => {
    const keys = FIELD_SPECS.map((spec) => spec.key);
    expect(new Set(keys).size).toBe(keys.length);
    expect(keys.sort()).toEqual(Object.keys(fieldsFrom(null)).sort());
    FIELD_SPECS.forEach((spec) => expect(spec.id).toMatch(/^img-/));
  });
});

describe('selectOptions', () => {
  it('reads the static lists for licence and slot', () => {
    expect(selectOptions({ options: 'license' })).toBe(LICENSE_OPTIONS);
    expect(selectOptions({ options: 'slot' })).toBe(SLOT_OPTIONS);
  });

  it('builds folder options from the folders given', () => {
    expect(selectOptions({ options: 'folder' }, { folders: ['default', 'aws'] })).toEqual([
      { value: 'default', label: 'default' },
      { value: 'aws', label: 'aws' },
    ]);
  });

  it('keeps a provider outside the common list selectable', () => {
    const common = selectOptions({ options: 'provider' }, { value: 'aws' });
    expect(common).toBe(COMMON_PROVIDERS);
    const rare = selectOptions({ options: 'provider' }, { value: 'oracle' });
    expect(rare.at(-1)).toEqual({ value: 'oracle', label: 'oracle' });
    expect(rare).toHaveLength(COMMON_PROVIDERS.length + 1);
  });

  it('is empty for an unknown source', () => {
    expect(selectOptions({ options: 'nope' })).toEqual([]);
  });
});

describe('factRows', () => {
  it('lists the known facts in order and skips the unknown ones', () => {
    const labels = factRows(ITEM).map((row) => row.label);
    expect(labels).toEqual([
      'Source',
      'Generated by',
      'Image set',
      'Dimensions',
      'Format',
      'Size',
      'Created',
      'Record',
    ]);
    const byLabel = Object.fromEntries(factRows(ITEM).map((row) => [row.label, row]));
    expect(byLabel['Generated by'].text).toBe('openai · gpt-image-1');
    expect(byLabel['Image set'].kind).toBe('set');
    expect(byLabel.Dimensions.text).toBe('1920 × 1080');
    expect(byLabel.Format.text).toBe('PNG');
    expect(byLabel.Size.text).toBe('2 KB');
    expect(byLabel.Record).toEqual({
      label: 'Record',
      kind: 'code',
      text: 'generated_content_images/img-1',
    });
  });

  it('shows an import URL as a link and the dates it has', () => {
    const rows = factRows({
      id: 'x',
      galleryCollection: 'c',
      source: 'import',
      sourceUrl: 'https://example.com/a.png',
      archivedAt: '2026-09-02T10:00:00Z',
      softDeletedAt: '2026-09-03T10:00:00Z',
      createdBy: 'saul',
    });
    const labels = rows.map((row) => row.label);
    expect(labels).toEqual([
      'Source',
      'Created',
      'Owner',
      'Archived',
      'Trashed',
      'Imported from',
      'Record',
    ]);
    expect(rows.find((row) => row.label === 'Imported from')).toMatchObject({
      kind: 'link',
      text: 'https://example.com/a.png',
    });
    expect(rows.find((row) => row.label === 'Created').text).toBe('Unknown');
  });
});

describe('the sentences', () => {
  it('describe the lineage from the set, the upload or the import', () => {
    expect(lineageSentence(ITEM)).toBe('Generated from the "Azure Chibi" image set (hero).');
    expect(lineageSentence({ source: 'upload' })).toBe('Uploaded by hand; no prompt lineage.');
    expect(lineageSentence({ source: 'import' })).toBe('Imported from a URL.');
    expect(lineageSentence({ source: 'ai-cover' })).toBe(
      'Generated without an image set; the built-in prompt applied.'
    );
  });

  it('count what points at the image before a permanent delete', () => {
    expect(deleteDescription(0)).toBe(
      'The record and its file are removed. This cannot be undone.'
    );
    expect(deleteDescription(1)).toMatch(/^1 content item point at this image/);
    expect(deleteDescription(3)).toMatch(/^3 content items point at this image/);
  });
});
