/**
 * The pure half of ImageDetailsDialog (ADR 0033): what the form edits, what
 * Save sends back, the facts list, the lineage sentence. Tables rather than
 * one JSX block per field, so each section component stays small enough to
 * read and the dialog itself only composes them.
 */
import {
  COMMON_PROVIDERS,
  formatBytes,
  formatDimensions,
  getSourceLabel,
  LICENSE_OPTIONS,
  SLOT_OPTIONS,
} from '@/lib/imageGallery';

export const selectClass =
  'w-full rounded-md border border-input bg-background px-2 py-1.5 text-sm focus:outline-none focus:ring-2 focus:ring-ring';

/**
 * The editable fields, in display order. `span` fills both grid columns;
 * `options` names which list a select is rendered from (see selectOptions).
 */
export const FIELD_SPECS = Object.freeze([
  { key: 'title', id: 'img-title', label: 'Title', kind: 'input', span: true },
  {
    key: 'altText',
    id: 'img-alt',
    label: 'Alt text',
    kind: 'input',
    span: true,
    placeholder: 'What the image shows, for readers who cannot see it',
  },
  { key: 'caption', id: 'img-caption', label: 'Caption', kind: 'textarea', span: true, rows: 2 },
  { key: 'license', id: 'img-license', label: 'Licence', kind: 'select', options: 'license' },
  {
    key: 'credit',
    id: 'img-credit',
    label: 'Credit',
    kind: 'input',
    placeholder: 'Photographer, source or model',
  },
  { key: 'folder', id: 'img-folder', label: 'Folder', kind: 'select', options: 'folder' },
  { key: 'provider', id: 'img-provider', label: 'Provider', kind: 'select', options: 'provider' },
  { key: 'slot', id: 'img-slot', label: 'Slot', kind: 'select', options: 'slot' },
  {
    key: 'tags',
    id: 'img-tags',
    label: 'Tags (comma-separated)',
    kind: 'input',
    className: 'font-mono text-xs',
  },
]);

const TEXT_KEYS = ['title', 'altText', 'caption', 'license', 'credit'];

/** The form's initial values for one gallery item (or an empty form). */
export function fieldsFrom(item) {
  const it = item || {};
  const fields = Object.fromEntries(TEXT_KEYS.map((key) => [key, it[key] || '']));
  fields.tags = (it.customTags || []).join(', ');
  fields.folder = it.folder || 'default';
  fields.provider = String(it.provider || '').toLowerCase();
  fields.slot = it.slot || '';
  return fields;
}

/** What Save sends: the fields as the record stores them. */
export function fieldsToPatch(fields) {
  return {
    title: fields.title,
    altText: fields.altText,
    caption: fields.caption,
    license: fields.license,
    credit: fields.credit,
    customTags: fields.tags
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean),
    folder: fields.folder,
    provider: fields.provider,
    slot: fields.slot,
  };
}

/** A provider outside the common list still shows as the selected option. */
function providerOptions(value) {
  const known = COMMON_PROVIDERS.some((o) => o.value === value);
  return value && !known ? [...COMMON_PROVIDERS, { value, label: value }] : COMMON_PROVIDERS;
}

const OPTION_SOURCES = {
  license: () => LICENSE_OPTIONS,
  slot: () => SLOT_OPTIONS,
  folder: ({ folders }) => folders.map((f) => ({ value: f, label: f })),
  provider: ({ value }) => providerOptions(value),
};

/** The `{ value, label }` list a select field renders. */
export function selectOptions(spec, { folders = [], value = '' } = {}) {
  const source = OPTION_SOURCES[spec.options];
  return source ? source({ folders, value }) : [];
}

export function formatDate(value) {
  if (!value) return 'Unknown';
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? 'Unknown' : date.toLocaleString();
}

/** One sentence on where the image came from. */
export function lineageSentence(item) {
  if (item.promptSet) {
    const prompt = item.promptName ? ` (${item.promptName})` : '';
    return `Generated from the "${item.promptSet}" image set${prompt}.`;
  }
  if (item.source === 'upload') return 'Uploaded by hand; no prompt lineage.';
  if (item.source === 'import') return `Imported from ${item.sourceUrl || 'a URL'}.`;
  return 'Generated without an image set; the built-in prompt applied.';
}

/**
 * The facts shown under the preview, in order, with the empty ones dropped.
 * `kind` picks the rendering: plain text unless it says `set` (a link to the
 * image set), `link` (an external URL) or `code`.
 */
export function factRows(item) {
  const whenPresent = (value, format) => (value ? format(value) : '');
  return [
    { label: 'Source', text: getSourceLabel(item.source) },
    {
      label: 'Generated by',
      text: [item.imageProvider, item.imageModel].filter(Boolean).join(' · '),
    },
    { label: 'Image set', kind: 'set', text: item.promptSet },
    { label: 'Dimensions', text: formatDimensions(item) },
    { label: 'Format', text: whenPresent(item.format, (f) => f.toUpperCase()) },
    { label: 'Size', text: whenPresent(item.bytes, formatBytes) },
    { label: 'Created', text: formatDate(item.createdAt) },
    { label: 'Owner', text: item.createdBy },
    { label: 'Archived', text: whenPresent(item.archivedAt, formatDate) },
    { label: 'Trashed', text: whenPresent(item.softDeletedAt, formatDate) },
    { label: 'Imported from', kind: 'link', text: item.sourceUrl },
    { label: 'Record', kind: 'code', text: `${item.galleryCollection}/${item.id}` },
  ].filter((row) => Boolean(row.text));
}

/** The confirm text for a permanent delete, counting what points at the image. */
export function deleteDescription(usedByCount) {
  if (!usedByCount) return 'The record and its file are removed. This cannot be undone.';
  const noun = usedByCount === 1 ? 'content item' : 'content items';
  return `${usedByCount} ${noun} point at this image and will lose it. The file is removed unless another record shares it. This cannot be undone.`;
}
