/**
 * "Explain this component" (#670, Phase 4 of #657): a button in the teaches
 * panel that sends the focused component, the build and the catalogue's own
 * text to `POST public/cloud-tools/explain` with `kind: "landing-zone"`, and
 * shows the two paragraphs that come back, labelled as generated. Modelled
 * on scenario/ExplainButton.jsx, which explains a pricing comparison through
 * the same route; the body's `kind` is what tells the server which it is.
 *
 * ONLY ON A CLICK. Nothing here fetches on mount, on a focus change or on a
 * build change: an explanation costs a model call and counts against the
 * reader's five an hour, shared with the pricing page, so it is asked for,
 * never assumed. The answer is keyed to the exact body it explained — focus
 * another component or change the build and the panel goes away rather than
 * describing a landing zone that is no longer on the page — and that key is
 * compared during render, so there is no effect and no setState in one.
 *
 * THE BODY IS WHAT THE SERVER'S VALIDATOR TAKES, AND NOTHING ELSE.
 * functions/src/lib/cloud-tools/explain/kinds/landingZone.js refuses unknown
 * keys, so `explanationRequest` builds the five fields by name from the
 * normalised state: every value the state can hold already passes the
 * page's own validators, which are the server's or stricter (the same
 * region and management-group patterns, counts capped at 5 against the
 * server's 20, eight ids against a cap of twelve, the longest `teaches` at
 * 970 characters against a cap of 1,200). The test copies the server's
 * allowlist and checks every component's body against it.
 */
import React, { useState } from 'react';
import { Loader2, RefreshCw, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { formatLocalDateTime } from '@/lib/cloudPricing';
import { OPTION_IDS, componentById, normalizeState } from '@/lib/landingZone';
import { requestLandingZoneExplanation } from '@/lib/publicApi';

/** The `kind` the server dispatches on (kinds/landingZone.js LANDING_ZONE_KIND_ID). */
export const LANDING_ZONE_EXPLAIN_KIND = 'landing-zone';

/** The component the panel shows for an id it does not know: the same fallback as LzTeaches. */
const FALLBACK_COMPONENT = 'management-groups';

/**
 * The request body: `{ kind, componentId, selected, options, teaches }`, the
 * five keys the server allows and no other. `selected` is the normalised
 * selection in catalogue order; `options` is every knob by its id; `teaches`
 * is the catalogue's hand-written text for the component, which the page
 * already shows.
 *
 * @param {object} args
 * @param {object} args.state  the build, normalised here again so a caller cannot send a raw one
 * @param {string} args.componentId  the focused component
 */
export function explanationRequest({ state, componentId }) {
  const component = componentById(componentId) ?? componentById(FALLBACK_COMPONENT);
  const normalized = normalizeState(state);
  return {
    kind: LANDING_ZONE_EXPLAIN_KIND,
    componentId: component.id,
    selected: [...normalized.selected],
    options: Object.fromEntries(OPTION_IDS.map((id) => [id, normalized.options[id]])),
    teaches: component.teaches,
  };
}

const paragraphs = (text) =>
  String(text)
    .split(/\n\s*\n/)
    .map((s) => s.trim())
    .filter(Boolean);

function Explanation({ explanation }) {
  return (
    <div
      className="flex flex-col gap-3 rounded-lg border border-slate-200 bg-slate-50 p-4 text-sm dark:border-slate-700 dark:bg-slate-900"
      data-testid="lz-explanation"
      data-cached={explanation.cached ? 'true' : undefined}
    >
      <p className="text-xs font-medium uppercase tracking-wider text-slate-600 dark:text-slate-400">
        Generated by AI about this build — check the module documentation before relying on it
      </p>
      {paragraphs(explanation.text).map((paragraph, index) => (
        <p key={index} className="text-slate-800 dark:text-slate-200">
          {paragraph}
        </p>
      ))}
      <p className="text-xs text-slate-600 dark:text-slate-400">
        {explanation.model} · {formatLocalDateTime(explanation.generatedAt)}
        {explanation.cached
          ? ' · cached: the same component in the same build was explained recently, so this is that answer'
          : ''}
      </p>
    </div>
  );
}

function Failure({ error, onRetry }) {
  let text;
  if (error.status === 429)
    text = 'Explanations are limited to a few an hour. Try again in a while.';
  else if (error.status === 503) text = error.message;
  else text = `The explanation could not be generated: ${error.message}`;
  return (
    <div
      role="alert"
      className="flex flex-wrap items-center gap-3 rounded-lg border border-destructive/40 bg-destructive/5 p-3 text-sm"
      data-status={error.status ?? 'error'}
    >
      <p className="min-w-0 flex-1 break-words">{text}</p>
      {error.status === 429 || error.status === 503 ? null : (
        <Button variant="outline" size="sm" onClick={onRetry}>
          <RefreshCw className="mr-2 h-3.5 w-3.5" /> Retry
        </Button>
      )}
    </div>
  );
}

/**
 * @param {object} props
 * @param {object} props.state  the normalised build
 * @param {string} props.componentId  the focused component, the one the teaches panel shows
 */
export function LzExplainButton({ state, componentId }) {
  const body = explanationRequest({ state, componentId });
  const key = JSON.stringify(body);
  // One record: which body it is about, and where the request got to.
  const [record, setRecord] = useState(null);
  const current = record?.key === key ? record : null;
  const loading = current?.status === 'loading';

  const ask = () => {
    setRecord({ key, status: 'loading' });
    requestLandingZoneExplanation(body).then(
      (explanation) =>
        setRecord((prev) => (prev?.key === key ? { key, status: 'done', explanation } : prev)),
      (error) => setRecord((prev) => (prev?.key === key ? { key, status: 'error', error } : prev))
    );
  };

  return (
    <>
      <Button
        type="button"
        variant="outline"
        size="sm"
        onClick={ask}
        disabled={loading}
        title="Ask the AI provider for two paragraphs about this component in this build."
        data-testid="lz-explain-button"
      >
        {loading ? (
          <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" aria-hidden="true" />
        ) : (
          <Sparkles className="mr-2 h-3.5 w-3.5" aria-hidden="true" />
        )}
        {loading ? 'Explaining…' : 'Explain this component'}
      </Button>
      {current?.status === 'done' ? (
        <div className="basis-full">
          <Explanation explanation={current.explanation} />
        </div>
      ) : null}
      {current?.status === 'error' ? (
        <div className="basis-full">
          <Failure error={current.error} onRetry={ask} />
        </div>
      ) : null}
    </>
  );
}
