/**
 * "Explain this component" (#670, Phase 4 of #657): a button in the teaches
 * panel that sends the focused component, the build and the catalogue's own
 * text to `POST public/cloud-tools/explain` with `kind: "landing-zone"`, and
 * shows the two paragraphs that come back, labelled as generated. The
 * button, the answer panel, the failure panel and the click-only rule are
 * ../explain/ExplainControl.jsx, shared with the pricing comparison's button;
 * this file is what the Landing Zone Builder sends and the words it uses.
 * The body's `kind` is what tells the server which it is.
 *
 * THE BODY IS WHAT THE SERVER'S VALIDATOR TAKES, AND NOTHING ELSE.
 * functions/src/lib/cloud-tools/explain/kinds/landingZone.js refuses unknown
 * keys, so `explanationRequest` builds the five fields by name from the
 * normalised state: every value the state can hold already passes the
 * page's own validators, which are the server's or stricter (the same
 * region and management-group patterns, counts capped at 5 against the
 * server's 20, eight ids against a cap of twelve, the longest `teaches` at
 * 970 characters against a cap of 1,200). The test copies the server's
 * allowlist and checks every component's body against it.
 */
import React from 'react';
import { OPTION_IDS, componentById, normalizeState } from '@/lib/landingZone';
import { requestLandingZoneExplanation } from '@/lib/publicApi';
import { ExplainControl } from '../explain/ExplainControl';

/** The `kind` the server dispatches on (kinds/landingZone.js LANDING_ZONE_KIND_ID). */
export const LANDING_ZONE_EXPLAIN_KIND = 'landing-zone';

/** The component the panel shows for an id it does not know: the same fallback as LzTeaches. */
const FALLBACK_COMPONENT = 'management-groups';

/**
 * The request body: `{ kind, componentId, selected, options, teaches }`, the
 * five keys the server allows and no other. `selected` is the normalised
 * selection in catalogue order; `options` is every knob by its id; `teaches`
 * is the catalogue's hand-written text for the component, which the page
 * already shows.
 *
 * @param {object} args
 * @param {object} args.state  the build, normalised here again so a caller cannot send a raw one
 * @param {string} args.componentId  the focused component
 */
export function explanationRequest({ state, componentId }) {
  const component = componentById(componentId) ?? componentById(FALLBACK_COMPONENT);
  const normalized = normalizeState(state);
  return {
    kind: LANDING_ZONE_EXPLAIN_KIND,
    componentId: component.id,
    selected: [...normalized.selected],
    options: Object.fromEntries(OPTION_IDS.map((id) => [id, normalized.options[id]])),
    teaches: component.teaches,
  };
}

const LABELS = Object.freeze({
  idle: 'Explain this component',
  busy: 'Explaining…',
  generated:
    'Generated by AI about this build — check the module documentation before relying on it',
  cached:
    'cached: the same component in the same build was explained recently, so this is that answer',
});

/**
 * @param {object} props
 * @param {object} props.state  the normalised build
 * @param {string} props.componentId  the focused component, the one the teaches panel shows
 */
export function LzExplainButton({ state, componentId }) {
  return (
    <ExplainControl
      body={explanationRequest({ state, componentId })}
      request={requestLandingZoneExplanation}
      labels={LABELS}
      title="Ask the AI provider for two paragraphs about this component in this build."
      testIds={{ button: 'lz-explain-button', panel: 'lz-explanation' }}
    />
  );
}
