import React from 'react';
import { routes, staticRoutes } from '@/lib/routeFactory';
import HeroImageCarousel from '@/components/landing/HeroImageCarousel';
import ProviderLandingTemplate from '@/components/shared/ProviderLandingTemplate';
import { ComingSoon, PlaceholderLink } from './DockerPlaceholderPage';

// Generated by scripts/generate-brand-art.mjs (npm run art:generate) from the
// Docker palette, like Terraform's rotation (#775). Replace any file one for
// one to swap in real artwork. scripts/hero-assets-exist.test.js fails on a
// path listed here that is not under public/.
export const DOCKER_HERO_IMAGES = [
  '/images/docker-hero/1.png',
  '/images/docker-hero/2.png',
  '/images/docker-hero/3.png',
  '/images/docker-hero/4.png',
  '/images/docker-hero/5.png',
];

/*
 * Docker as a service provider (owner request 2026-09-28): the Terraform
 * landing page's template, with three focus areas, each linking to its own
 * page as Terraform's sections link to theirs: building images (#772), the
 * Docker Desktop app (#773) and the sandbox recipe (#774). An area marked
 * `available` says so and shows its link; one without it would say what it
 * will cover and that it is coming, which no area does today. Nothing here
 * reads the content API, and the template's live-content panel is off,
 * because the guides are pages of their own rather than published articles.
 *
 * Facts the first area states, from lab-image/: one Dockerfile with two final
 * targets, every direct download checked against a pinned checksum (versions.env),
 * and the publish workflow attaching a provenance attestation.
 */

export const FOCUS_AREAS = [
  {
    id: 'building-images',
    eyebrow: 'FOCUS AREA · IMAGES',
    title: 'Building images',
    icon: 'deployed_code',
    text: 'Writing Dockerfiles that stay small and quick to rebuild, multi-stage builds that keep build tools out of the image you ship, and provenance attestations that record how an image was made. The worked example is hcw-lab, the image every browser lab on this site runs: one Dockerfile, two build targets, and every direct download checked against a pinned checksum.',
    tags: ['Dockerfiles', 'Multi-stage builds', 'Provenance'],
    available: true,
    link: { label: 'Read the guide to building images', to: routes.buildingImages('docker') },
  },
  {
    id: 'docker-desktop',
    eyebrow: 'FOCUS AREA · DESKTOP',
    title: 'The Docker Desktop app',
    icon: 'desktop_windows',
    text: 'Installing Docker Desktop on Windows and macOS, then using it day to day: running and inspecting containers, managing images and volumes, the WSL 2 backend and resource limits, running the lab image, and how the app relates to Docker Engine on a Linux server.',
    tags: ['Install', 'Containers', 'Images and volumes'],
    available: true,
    link: { label: 'Read the Docker Desktop guide', to: routes.desktop('docker') },
  },
  {
    id: 'agent-sandbox',
    eyebrow: 'FOCUS AREA · SANDBOXES',
    title: 'Running an agent in a sandbox',
    icon: 'shield_person',
    text: 'Docker Sandboxes run a coding agent in an isolated microVM on your own machine, with only the folder you give it. The recipe points one at a landing zone from the Landing Zone Builder, so the agent can validate and explain the Terraform without ever planning or applying it.',
    tags: ['Docker Sandboxes', 'Coding agents', 'Landing zones'],
    available: true,
    link: { label: 'Run an agent in a sandbox', to: routes.sandboxes('docker') },
  },
];

/** The counterpart of `ComingSoon` for an area whose page exists. */
function AvailableNow() {
  return (
    <p className="mb-0 inline-flex w-fit items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-primary dark:text-(--slate-blue)">
      <span className="material-symbols-outlined text-sm" aria-hidden="true">
        check_circle
      </span>
      Available now
    </p>
  );
}

function FocusArea({ area }) {
  return (
    <article className="glass rounded-xl overflow-hidden flex flex-col" data-testid={area.id}>
      <div className="h-2 w-full bg-primary/60" aria-hidden="true" />
      <div className="p-6 flex flex-col gap-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="size-10 shrink-0 rounded-full bg-primary/10 flex items-center justify-center text-primary dark:text-(--slate-blue)">
            <span className="material-symbols-outlined text-xl" aria-hidden="true">
              {area.icon}
            </span>
          </div>
          {area.available ? <AvailableNow /> : <ComingSoon />}
        </div>
        <p className="max-w-3xl text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          {area.text}
        </p>
        <ul className="flex flex-wrap gap-1.5" aria-label="Topics">
          {area.tags.map((tag) => (
            <li
              key={tag}
              className="text-[11px] bg-slate-200 text-slate-800 dark:bg-slate-700 dark:text-slate-200 px-2 py-0.5 rounded"
            >
              {tag}
            </li>
          ))}
        </ul>
        {area.link && (
          <div>
            <PlaceholderLink link={area.link} />
          </div>
        )}
      </div>
    </article>
  );
}

export default function DockerLandingPage() {
  return (
    <ProviderLandingTemplate
      provider="docker"
      hero={{
        eyebrow: 'IMAGES · DESKTOP · SANDBOXES',
        title: (
          <>
            Container intelligence with <span className="display-accent">Docker</span>
          </>
        ),
        description:
          'Three guides you can follow today: building container images, using the Docker Desktop app day to day, and running a coding agent in a sandbox. The worked example is the image behind this site’s own browser labs.',
        media: (
          <HeroImageCarousel
            images={DOCKER_HERO_IMAGES}
            intervalMs={3000}
            fadeMs={800}
            alt="Docker container imagery"
          />
        ),
        cta: { label: 'Explore the browser labs', to: staticRoutes.labs },
      }}
      sections={FOCUS_AREAS.map((area) => ({
        eyebrow: area.eyebrow,
        title: area.title,
        content: <FocusArea area={area} />,
      }))}
      latestContent={false}
    />
  );
}
