/**
 * `README.md` (#667): what is in the build, the files, the validated
 * pattern's prerequisites, the module pins, and the line that says these
 * files were generated for learning and never applied here.
 */
import { AVM_MODULES, AVM_VERIFIED_ON, TERRAFORM_REQUIRED_VERSION } from '../avmVersions';
import { componentById, countOptionFor } from '../components';
import { file } from './format';

const INTRO = [
  '# Azure landing zone, generated for learning',
  '',
  'These files were generated by the HybridCloudWorks Landing Zone Builder from a',
  'selection of components, to show what each part of an Azure landing zone becomes in',
  'Terraform. They mirror HashiCorp’s validated pattern "Build an Azure landing zone',
  'with Terraform" and call the current Azure Verified Modules for it. **They were',
  'generated for learning and have never been applied by HybridCloudWorks.** Read them,',
  'compare them with the pattern, and if you run them, do it in a tenant you own, after',
  'a `terraform plan` you have read.',
  '',
  '## What is in this build',
  '',
];

const PREREQUISITES = [
  '## Prerequisites, from the validated pattern',
  '',
  '- An HCP Terraform organisation with a workspace connected to the repository these',
  '  files are committed to, holding the state and running the plans.',
  '- An Azure tenant in which the deploying identity has been granted Owner at the tenant',
  '  root scope (`/`), which is what creating management groups and assigning policy at',
  '  the root requires; a Global Administrator elevates access to grant it.',
  '- A service principal (or a workload identity federation credential) for the workspace,',
  '  with its tenant, client and subscription set as the workspace’s `ARM_TENANT_ID`,',
  '  `ARM_CLIENT_ID`, `ARM_CLIENT_SECRET` and `ARM_SUBSCRIPTION_ID` variables.',
  '- One subscription per platform role and per application landing zone, whose ids go',
  '  into `terraform.tfvars` (see `terraform.tfvars.example`).',
  `- Terraform ${TERRAFORM_REQUIRED_VERSION}.`,
  '',
];

const SPOKES = [
  '## How a landing zone is built',
  '',
  'Each landing zone, identity included, is a subscription that `alz.tf` places under',
  'its management group and a spoke virtual network, one /24 carved from the spoke range,',
  'that the virtual network module peers to the hub in both directions. Corp and identity',
  'spokes carry a route table whose default route points at the firewall when it is',
  'selected; online spokes egress directly.',
  '',
];

const RUNNING = [
  '## Running it',
  '',
  'From a checkout with `terraform.tfvars` filled in:',
  '',
  '```',
  'terraform init',
  'terraform plan',
  '```',
  '',
  'A landing zone creates resources that cost money every hour they exist: Azure',
  'Firewall, Bastion, the Log Analytics workspace and the DDoS plan if you enable one.',
  'Read the plan, and destroy what you built when the lesson is over.',
];

function componentLine(c, options) {
  const countId = countOptionFor(c.id);
  const count = countId ? ` (${options[countId]})` : '';
  const module = c.avm ? ` — \`${c.avm.source}\` ${c.avm.version}` : '';
  return `- **${c.label}${count}**: ${c.summary}${module}`;
}

export function readmeMd(state, emitted) {
  const selected = state.selected.map((id) => componentById(id));
  if (!selected.length) {
    return file('README.md', [
      ...INTRO,
      'Nothing yet. Select a component to see the Terraform it becomes.',
    ]);
  }
  return file('README.md', [
    ...INTRO,
    ...selected.map((c) => componentLine(c, state.options)),
    '',
    '## Files',
    '',
    ...emitted.map((f) => `- \`${f.path}\``),
    '',
    ...PREREQUISITES,
    ...SPOKES,
    '## Module versions',
    '',
    `Pinned to the versions the Terraform Registry listed on ${AVM_VERIFIED_ON}:`,
    '',
    ...Object.values(AVM_MODULES).map((m) => `- \`${m.source}\` ${m.version}`),
    '',
    ...RUNNING,
  ]);
}
