/** `terraform.tf` (#667): the required version and the four pinned providers. */
import { PROVIDER_PINS, TERRAFORM_REQUIRED_VERSION } from '../avmVersions';
import { block, file, obj, q } from './format';

export function terraformTf() {
  return file('terraform.tf', [
    '# Generated by the HybridCloudWorks Landing Zone Builder for learning. Never applied here.',
    ...block('terraform', [
      ['required_version', q(TERRAFORM_REQUIRED_VERSION)],
      '',
      ...block(
        'required_providers',
        PROVIDER_PINS.map((p) => [
          p.name,
          obj([
            ['source', q(p.source)],
            ['version', q(p.version)],
          ]),
        ])
      ),
    ]),
  ]);
}
