/**
 * The Images tab (ADR 0033): a sample generator that tries the set on a
 * subject without leaving the page, then every image carrying the set's
 * lineage — selected, rejected, in use — opening into the Image Gallery.
 */
import React from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import EmptyState from '@/components/admin/shared/EmptyState';
import StatusBadge from '@/components/admin/shared/StatusBadge';
import { resolveMediaUrl } from '@/lib/functionsBase';
import {
  imageState,
  inputClass,
  plural,
  sampleOptions,
  sampleProviderLine,
} from './promptSetEditorModel';

const SAMPLE_SELECTS = [
  { key: 'promptName', id: 'sample-prompt', label: 'Prompt' },
  { key: 'slot', id: 'sample-slot', label: 'Slot' },
  { key: 'provider', id: 'sample-provider', label: 'Provider' },
];
const SAMPLE_INPUTS = [
  { key: 'title', id: 'sample-title', label: 'Subject', placeholder: 'e.g. Scaling AKS with KEDA' },
  {
    key: 'summary',
    id: 'sample-summary',
    label: 'Context (optional)',
    placeholder: 'A sentence of context for the illustration',
    className: 'md:col-span-3',
  },
];

function SampleSelect({ field, value, options, onChange }) {
  return (
    <div>
      <label htmlFor={field.id} className="text-[11px] font-medium">
        {field.label}
      </label>
      <select
        id={field.id}
        value={value}
        onChange={(e) => onChange(field.key, e.target.value)}
        className={inputClass}
      >
        {options.map((option) => (
          <option key={option.value || 'none'} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
    </div>
  );
}

function SampleInput({ field, value, onChange }) {
  return (
    <div className={field.className}>
      <label htmlFor={field.id} className="text-[11px] font-medium">
        {field.label}
      </label>
      <Input
        id={field.id}
        value={value}
        onChange={(e) => onChange(field.key, e.target.value)}
        placeholder={field.placeholder}
      />
    </div>
  );
}

function GenerateButton({ sampling, disabled, onClick }) {
  const Icon = sampling ? Loader2 : Sparkles;
  return (
    <div className="flex items-end">
      <Button type="button" className="w-full gap-1" onClick={onClick} disabled={disabled}>
        <Icon className={`h-4 w-4${sampling ? ' animate-spin' : ''}`} aria-hidden="true" />
        {sampling ? 'Generating…' : 'Generate'}
      </Button>
    </div>
  );
}

function SampleResult({ result, setName }) {
  return (
    <div className="mt-3 grid grid-cols-1 gap-3 md:grid-cols-[240px_minmax(0,1fr)]">
      <img
        src={resolveMediaUrl(result.imageUrl)}
        alt={`Sample from ${setName}`}
        className="w-full rounded-lg border border-border object-cover"
      />
      <div className="space-y-1 text-xs">
        <p>
          <span className="font-medium">Generated by</span> {result.imageProvider}
          {sampleProviderLine(result)}
        </p>
        <p>
          <span className="font-medium">Template version</span> {result.promptTemplateVersion}
        </p>
        <details>
          <summary className="cursor-pointer font-medium">Prompt sent</summary>
          <pre className="mt-1 max-h-40 overflow-y-auto whitespace-pre-wrap rounded bg-muted/40 p-2 text-[11px]">
            {result.prompt}
          </pre>
        </details>
      </div>
    </div>
  );
}

function SamplePanel({ set, prompts, busy, state, actions }) {
  const options = sampleOptions(prompts);
  const locked = state.sampling || busy || Boolean(set?.archivedAt);
  return (
    <div className="rounded-lg border border-border p-3">
      <p className="flex items-center gap-1 text-sm font-semibold">
        <Sparkles className="h-4 w-4" aria-hidden="true" /> Generate a sample from this set
      </p>
      <p className="mt-1 text-xs text-muted-foreground">
        One hero through the same path the AI cover uses — primary prompt, the chosen prompt&apos;s
        hero template, style rules and the keyword matrix. The image lands in the gallery under this
        set. Each sample is billed by the image provider.
      </p>
      <div className="mt-2 grid grid-cols-1 gap-2 md:grid-cols-4">
        {SAMPLE_SELECTS.map((field) => (
          <SampleSelect
            key={field.key}
            field={field}
            value={state.sample[field.key]}
            options={options[field.key]}
            onChange={actions.setSampleField}
          />
        ))}
        {SAMPLE_INPUTS.map((field) => (
          <SampleInput
            key={field.key}
            field={field}
            value={state.sample[field.key]}
            onChange={actions.setSampleField}
          />
        ))}
        <GenerateButton sampling={state.sampling} disabled={locked} onClick={actions.runSample} />
      </div>
      {state.sampleError && (
        <p role="alert" className="mt-2 text-xs text-destructive">
          {state.sampleError}
        </p>
      )}
      {state.sampleResult && <SampleResult result={state.sampleResult} setName={set.name} />}
    </div>
  );
}

function ImageTile({ image, onOpen }) {
  return (
    <li className="overflow-hidden rounded-lg border border-border">
      <button
        type="button"
        className="block w-full focus:outline-none focus:ring-2 focus:ring-ring"
        onClick={() => onOpen(image)}
        title={image.title || image.id}
      >
        <img
          src={resolveMediaUrl(image.imageUrl)}
          alt={image.altText || image.title || ''}
          loading="lazy"
          className="aspect-video w-full object-cover"
        />
      </button>
      <div className="space-y-1 p-2 text-[10px]">
        <div className="flex flex-wrap gap-1">
          <StatusBadge status={imageState(image)} size="xs" />
          {image.usageCount > 0 && <Badge variant="secondary">In use ({image.usageCount})</Badge>}
          {image.slot && <Badge variant="outline">{image.slot}</Badge>}
        </div>
        <p className="truncate text-muted-foreground">
          {image.promptName ? `${image.promptName} · ` : ''}
          {image.promptTemplateVersion || ''}
        </p>
        <p className="truncate text-muted-foreground">
          {image.createdAt ? new Date(image.createdAt).toLocaleDateString() : ''}
        </p>
      </div>
    </li>
  );
}

function ImageGrid({ images, onOpenImage }) {
  if (images.length === 0) {
    return (
      <EmptyState
        compact
        title="No images from this set yet"
        description="Generate a sample above, or assign the set to a page and generate a cover from the review queue."
      />
    );
  }
  return (
    <ul
      className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6"
      aria-label="Images generated from this set"
    >
      {images.map((image) => (
        <ImageTile key={image.id} image={image} onOpen={onOpenImage} />
      ))}
    </ul>
  );
}

export default function ImagesTab({
  set,
  prompts,
  images,
  busy,
  state,
  actions,
  onOpenGallery,
  onOpenImage,
}) {
  const usageNote = state.imagesWithUsage ? '' : ' (usage loading…)';
  return (
    <>
      <SamplePanel set={set} prompts={prompts} busy={busy} state={state} actions={actions} />
      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">
          {plural(images.length, 'image')} carry this set&apos;s lineage
          {usageNote}
        </p>
        <Button type="button" variant="outline" size="sm" onClick={() => onOpenGallery(set.name)}>
          Open in Image Gallery
        </Button>
      </div>
      <ImageGrid images={images} onOpenImage={onOpenImage} />
    </>
  );
}
