import React from 'react';
import { ScrollTrigger } from '@/components/animations';

const INSIGHT_TYPES = {
  'weekly-digest': {
    label: 'Weekly Digest',
    icon: 'calendar_view_week',
    color: 'text-blue-300 border-blue-500/30 bg-blue-500/10',
  },
  trend: {
    label: 'Trend Analysis',
    icon: 'trending_up',
    color: 'text-purple-300 border-purple-500/30 bg-purple-500/10',
  },
  recommendation: {
    label: 'Recommendation',
    icon: 'lightbulb',
    color: 'text-amber-300 border-amber-500/30 bg-amber-500/10',
  },
  alert: {
    label: 'Alert',
    icon: 'warning',
    color: 'text-rose-300 border-rose-500/30 bg-rose-500/10',
  },
  summary: {
    label: 'Summary',
    icon: 'summarize',
    color: 'text-emerald-300 border-emerald-500/30 bg-emerald-500/10',
  },
  default: {
    label: 'Insight',
    icon: 'auto_awesome',
    color: 'text-primary border-primary/30 bg-primary/10',
  },
};

function formatTimestamp(timestamp) {
  if (!timestamp) return '';

  let date;
  if (timestamp.toDate) {
    date = timestamp.toDate();
  } else {
    date = new Date(timestamp);
  }

  if (isNaN(date.getTime())) return '';

  const now = new Date();
  const diffMs = now - date;
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffHours / 24);

  if (diffHours < 1) return 'Just now';
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;

  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

// ⚡ Bolt: Prevent unnecessary re-renders of individual insight cards when the parent panel updates
const InsightCard = React.memo(({ insight, index }) => {
  const typeConfig = INSIGHT_TYPES[insight.insightType] || INSIGHT_TYPES.default;
  const generatedBy = insight.generatedBy || 'AI Agent';
  const timestamp = formatTimestamp(insight.createdAt || insight.updatedAt || insight.timestamp);

  return (
    <ScrollTrigger animation="slideRight" duration={0.4} delay={index * 0.08}>
      <div
        className="p-4 rounded-xl border bg-white/5 dark:bg-slate-800/30 backdrop-blur-sm
        border-slate-200/20 dark:border-slate-700/50 hover:border-primary/40 transition-all duration-300"
      >
        <div className="flex items-start justify-between gap-2 mb-3">
          <span
            className={`inline-flex items-center gap-1.5 px-2 py-1 rounded-md border text-[10px] font-medium ${typeConfig.color}`}
          >
            <span className="material-symbols-outlined text-xs">{typeConfig.icon}</span>
            {typeConfig.label}
          </span>
          {timestamp && (
            <span className="text-[10px] text-slate-700 dark:text-slate-400">{timestamp}</span>
          )}
        </div>

        <h4 className="text-sm font-semibold text-slate-900 dark:text-white mb-2 line-clamp-2">
          {insight.title}
        </h4>

        <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed line-clamp-4 mb-3">
          {insight.insight || insight.summary || ''}
        </p>

        {insight.tags && insight.tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-3">
            {insight.tags.slice(0, 3).map((tag, tagIndex) => (
              <span
                key={tagIndex}
                className="px-1.5 py-0.5 bg-slate-700/30 dark:bg-slate-700/50 text-slate-700 dark:text-slate-300 text-[9px] rounded-full"
              >
                {tag}
              </span>
            ))}
          </div>
        )}

        <div className="pt-2 border-t border-slate-200/10 dark:border-slate-700/50">
          <span className="text-[10px] text-slate-700 dark:text-slate-400">
            Generated by {generatedBy}
          </span>
        </div>
      </div>
    </ScrollTrigger>
  );
});

InsightCard.displayName = 'InsightCard';

function InsightsSkeleton() {
  return (
    <div className="space-y-3">
      {[...Array(4)].map((_, i) => (
        <div
          key={i}
          className="p-4 rounded-xl border border-slate-700/50 bg-slate-800/30 animate-pulse"
        >
          <div className="space-y-3">
            <div className="h-4 bg-slate-700/40 rounded w-1/3" />
            <div className="h-3 bg-slate-700/30 rounded w-full" />
            <div className="h-2.5 bg-slate-700/20 rounded w-4/5" />
          </div>
        </div>
      ))}
    </div>
  );
}

export default function AiInsightsPanel({ insights = [], loading = false }) {
  if (loading) {
    return <InsightsSkeleton />;
  }

  if (insights.length === 0) {
    return (
      <div className="rounded-xl border border-slate-200/20 dark:border-slate-700/50 bg-white/5 dark:bg-slate-800/20 backdrop-blur-sm p-6 text-center">
        <span className="material-symbols-outlined text-4xl text-slate-500 mb-2">auto_awesome</span>
        <p className="text-sm text-slate-700 dark:text-slate-300">No AI insights available</p>
      </div>
    );
  }

  return (
    <aside className="space-y-4">
      <div className="flex items-center gap-2 mb-2">
        <span className="material-symbols-outlined text-primary text-lg">auto_awesome</span>
        <h2 className="font-bold text-slate-900 dark:text-white text-sm uppercase tracking-wide">
          AI Insights
        </h2>
      </div>

      <p className="text-xs text-slate-700 dark:text-slate-300 mb-4">
        Generated analysis from HCW specialist agents
      </p>

      <div className="space-y-3 max-h-[900px] overflow-y-auto custom-scrollbar pr-1">
        {insights.slice(0, 10).map((insight, index) => (
          <InsightCard key={insight.id || index} insight={insight} index={index} />
        ))}
      </div>
    </aside>
  );
}
